# Generated by Django 4.0.4 on 2022-05-20 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='owner',
        ),
    ]
