# Generated by Django 4.0.4 on 2022-05-20 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_select_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('input', 'input'), ('textarea', 'textarea'), ('select', 'select ')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
