# Generated by Django 4.0.4 on 2022-05-21 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_question_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_select_answers', to='question.question')),
                ('select', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='select_answers', to='question.select')),
            ],
        ),
    ]
